### ISSUE TITLE
Request to add alternative anime source

### ISSUE THREAD

**Issue by ArijitKHaldar** [ksyasuda/aniwrapper#1]
Would it be possible to add alternative anime source such as `https://animefox.io/` or any other, if one source fails sometimes.

**Comment by ksyasuda** [comment]
As it currently stands, I do not believe it is possible without major modifications to the main script.  It may be possible to use a difference server on gogoanime and I'll look into that.   When I have more time, I want to rewrite this script in python since I have much more experience with the language and it will give me the opportunity to refactor the code to make adding features like this much easier
