### ISSUE TITLE
Autoplay next episode

### ISSUE THREAD

**Issue by AdalynBlack** [ksyasuda/aniwrapper#4]
It would be nice if Aniwrapper would autoplay the next episode after the current one finishes. As is, MPV simply stops playing, and you need to reopen Aniwrapper and select the next episode manually

**Comment by ksyasuda** [comment]
I'm against having autoplay be enabled by default, but I think it'd be good to have it toggleable through flags

The issue I see with implementing true autoplay is that if you lose access to the command-line menu, there would only be 3 ways to stop the program
1. Manually kill the process
2. Wait for all episodes to be completed/exited
3. Implement a new flag for killing a running `aniwrapper`

One solution I've come up for this, #5, utilizes a 'Continue watching' prompt at the end of each episode so that you can easily continue on to the next episode while never losing control of when to stop watching
<div align='center'>
<img src="https://user-images.githubusercontent.com/33813108/172029734-2ff6f2db-03bd-449b-81c0-bf429d67f77a.png">
</div>

I'll play around with the idea of setting a minimum number of episodes to autoplay before prompting to continue, but with a large enough minimum number, the same issues mentioned above still apply
